File structure reorg
JuniLearning/eslint-config-juni pull request #11
Opened 2020-09-02 16:24 UTC by tristan-kenneth-tarpley

Reorganized the file structure to include various configs that can be included according to the environment (in the `packages` folder). 

It's similar to Airbnb's config, but differs in that they have each folder in `packages` as its own separate npm package. I haven't tested integrating this with one of our repos yet because I don't want to publish a non-master branch to the npm repo, but we should be able to include the configs in a project by adding:
```json
extends: [
  'juni/base'
]
```

or 

```json
extends: [
  'juni/react'
]
```

I will start a stacked branch on this that includes rules for typescript and react-typescript. 

*Side question:*
Do you think we need a specific config for Node? Or should that be covered in `/base`?

2020-09-02 16:26 UTC, Restuta commented
Fee free to publish non master to npm, I don’t think there is any harm in that atm :)

2020-09-03 00:34 UTC, Restuta requested changes
That is a good starting point, thank you!

2020-09-03 00:34 UTC, Restuta commented on README.md
> +3. Available config options at the moment are 'base' and 'react'. If you include 'react' in your project, it will also include 'base,' but not vice-versa. Include them accordingly based on the enviro
I'd suggest creating a copy of these steps for Backend and Frontend (React) projects, so it's easier to follow step by step and run exact commands vs trying to figure out what is the correct setup using this step 3.

2020-09-03 00:34 UTC, Restuta commented on README.md
> +  extends: ["juni/react"],
nit: I am not sure why it's double quotes now.

2020-09-03 00:34 UTC, Restuta commented on packages/base/rules/best-practices.js
> +    ],
For consiceness can we try and collapse rule definitions to be a single line? Just for this file I think it makes sense, feel free to add `//prettier-ignore`
```suggestion
    'no-param-reassign': [ 2, { props: false } ],
```

2020-09-03 00:34 UTC, Restuta commented on packages/base/rules/styles.js
> +    'consistent-return': 0
Let's add a comment to each and every rule explaining why we are disabling / re-configuring it. Applies to all custom config files.

2020-09-03 15:59 UTC, tristan-kenneth-tarpley commented on packages/base/rules/styles.js
> +    'consistent-return': 0
Ok. I was also planning to write up documentation in a style guide similar to how AirBnB did.

2020-09-03 16:09 UTC, tristan-kenneth-tarpley commented on README.md
> +  extends: ["juni/react"],
Oh, this is in our README. This is probably just my fault.

2020-09-03 16:40 UTC, Restuta commented on packages/base/rules/styles.js
> +    'consistent-return': 0
Not sure how they did it, do you have an example? But I meant directly in code

2020-09-03 16:43 UTC, tristan-kenneth-tarpley commented on packages/base/rules/styles.js
> +    'consistent-return': 0
They have all of their base styles in their root README: https://github.com/airbnb/javascript/blob/master/README.md

They also have various other READMEs on different styling.

css-in-js style guide doc: https://github.com/airbnb/javascript/blob/master/css-in-javascript/README.md

React style guide doc: https://github.com/airbnb/javascript/blob/master/react/README.md

2020-09-03 17:59 UTC, tristan-kenneth-tarpley commented on packages/base/rules/styles.js
> +    'consistent-return': 0
@Restuta This will take a good chunk of time to write out. Should we go ahead and merge this PR first and I can write the style guides as a follow-up PR?

2020-09-03 17:59 UTC, tristan-kenneth-tarpley commented
@Restuta re-requesting. Will update in a moment with a link to a frontend integration branch.

2020-09-16 17:52 UTC, Restuta commented on packages/base/rules/styles.js
> +    'consistent-return': 0
Yeah I think if we are reusing styles, we should only document differences?

2020-09-16 17:52 UTC, Restuta commented
>Do you think we should add a section in the README about integrating lint-prepush?

Yes

2020-09-16 17:57 UTC, Restuta approved these changes

2020-09-16 17:57 UTC, Restuta commented on test.js
> +  lukeSkywalker,
⚔️ + ⚡

2020-09-17 21:48 UTC, merged