Less strict rules
JuniLearning/eslint-config-juni pull request #12
Opened 2020-09-18 21:00 UTC by tristan-kenneth-tarpley

Adjusted rules to be less strict than the original version. Trying to balance cost of implementation vs. appearance in the Juni codebase. My goal is not to get to inbox 0, but include the preferred ruleset, and allow for easy incremental refactoring on old areas of the codebase over time.

Current [eslint-nibble](https://github.com/IanVS/eslint-nibble) count on FE codebase after running `lint:fix`:
*note that I left `react/prop-types` as a warning, because that would be a good area to refactor in the future, though pretty high cost. I wouldn't be at all opposed to removing altogether, though*

![Screen Shot 2020-09-18 at 3 58 52 PM](https://user-images.githubusercontent.com/36747395/93644581-e9877c00-f9c7-11ea-9e20-3767a358e7dd.png)

Opening this PR for a source of discussion other rules to disable.

2020-09-21 15:31 UTC, tristan-kenneth-tarpley commented
Ran eslint-nibble again after disabling `prop-types`. Do you think this is a minimum viable ruleset, @Restuta? 

<img width="817" alt="Screen Shot 2020-09-21 at 10 29 18 AM" src="https://user-images.githubusercontent.com/36747395/93786904-7400f300-fbf5-11ea-9ecb-b21d5dd4edfd.png">

2020-09-23 22:10 UTC, Restuta commented
@tristan-kenneth-tarpley hard to say, but let's say yes, we can debate other rules one-by-one in slack, for now let's say it's a good starting point.

2020-09-23 22:14 UTC, Restuta requested changes
Let's add reasons for disabling rules. That is most important at this stage. It would be nice to point out:

1) Are we disabling this rule permanently or temporarily
2) If permanently – why?

2020-09-23 22:14 UTC, Restuta commented on packages/base/rules/best-practices.js
> +    // enforces a certain number of classes per file, defaults to 1. Enabled due to several files with multiple, smaller React Class components
Did you mean? 
```suggestion
    // enforces a certain number of classes per file, defaults to 1. Disabled due to several files with multiple, smaller React Class components
```

2020-09-23 22:14 UTC, Restuta commented on packages/base/rules/best-practices.js
> +    'no-nested-ternary': 0,
We should provide a reason for disabling. Nested ternaries most of the times are confusing I'd rather add 

`// eslint-ignore no-nested-ternary`

When we feel like it's not an issue

2020-09-23 22:14 UTC, Restuta commented on packages/base/rules/imports.js
> +    'import/prefer-default-export': 0,
Same here we should provide not only rule descriptions but also reasons for disabling those.

2020-09-24 16:30 UTC, tristan-kenneth-tarpley commented on packages/base/rules/best-practices.js
> +    'no-nested-ternary': 0,
The majority of the descriptions at this point would be, "disabled for backwards compatibility." I guess that's okay, though.

2020-09-24 17:29 UTC, Restuta commented on packages/base/rules/best-practices.js
> +    'no-nested-ternary': 0,
That is fine, maybe we can add a section?

```js
/* Disabled for backwards compatibility 
    Will be enabled and fixed one-by-one in the nearest future.
  */

```

2020-09-24 20:31 UTC, tristan-kenneth-tarpley commented
@Restuta Can we get this approved/merged before beginning the integration so people can reference master?

2020-09-24 20:53 UTC, Restuta approved these changes

2020-09-24 20:54 UTC, merged